#define _GNU_SOURCE
#include <arpa/inet.h>
#include <errno.h>
#include <json-c/json.h>
#include <netinet/in.h>
#include <poll.h>
#include <signal.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <sys/socket.h>
#include <sys/un.h>
#include <unistd.h>

#define SOCK_PATH "/var/run/parental-control.sock"
#define WWW "/usr/share/parental-control/www"
#define SETTINGS "/etc/parental-control/settings.json"
#define MAX_PAYLOAD (1024u*1024u)

static int sendall(int fd,const void *p,size_t n){const unsigned char*s=p;while(n){ssize_t w=write(fd,s,n);if(w<0){if(errno==EINTR)continue;return-1;}if(!w)return-1;s+=w;n-=w;}return 0;}
static int recvall(int fd,void *p,size_t n){unsigned char*s=p;while(n){ssize_t r=read(fd,s,n);if(r<0){if(errno==EINTR)continue;return-1;}if(!r)return 0;s+=r;n-=r;}return 1;}
static ssize_t read_headers(int fd,char*b,size_t cap){size_t used=0;while(used+1<cap){ssize_t r=read(fd,b+used,cap-used-1);if(r<0){if(errno==EINTR)continue;return-1;}if(!r)break;used+=(size_t)r;b[used]=0;if(strstr(b,"\r\n\r\n"))return(ssize_t)used;}return-1;}
static void reply(int fd,int code,const char*status,const char*ct,const void*body,size_t n){char h[768];int m=snprintf(h,sizeof h,"HTTP/1.1 %d %s\r\nContent-Type: %s\r\nContent-Length: %zu\r\nCache-Control: no-store\r\nConnection: close\r\n\r\n",code,status,ct,n);if(m>0){sendall(fd,h,(size_t)m);sendall(fd,body,n);}}
static const char*mime(const char*p){size_t n=strlen(p);if(n>4&&!strcmp(p+n-4,".css"))return"text/css";if(n>3&&!strcmp(p+n-3,".js"))return"application/javascript";if(n>5&&!strcmp(p+n-5,".json"))return"application/manifest+json";if(n>4&&!strcmp(p+n-4,".svg"))return"image/svg+xml";return"text/html; charset=utf-8";}
static void static_file(int c,const char*path){char clean[256];int pn=snprintf(clean,sizeof clean,"%s",path);if(pn<0||(size_t)pn>=sizeof clean){const char*e="{\"success\":false}";reply(c,414,"URI Too Long","application/json",e,strlen(e));return;}char*q=strchr(clean,'?');if(q)*q=0;const char*name=!strcmp(clean,"/")?"index.html":clean+1;if(strstr(name,"..")){const char*e="{\"success\":false}";reply(c,400,"Bad Request","application/json",e,strlen(e));return;}char f[512];int fn=snprintf(f,sizeof f,"%s/%s",WWW,name);if(fn<0||(size_t)fn>=sizeof f){const char*e="{\"success\":false}";reply(c,414,"URI Too Long","application/json",e,strlen(e));return;}FILE*fp=fopen(f,"rb");if(!fp){const char*e="{\"success\":false}";reply(c,404,"Not Found","application/json",e,strlen(e));return;}if(fseek(fp,0,SEEK_END)!=0){fclose(fp);const char*e="{\"success\":false}";reply(c,500,"Internal Server Error","application/json",e,strlen(e));return;}long ln=ftell(fp);if(ln<0||ln>(long)(4*MAX_PAYLOAD)||fseek(fp,0,SEEK_SET)!=0){fclose(fp);const char*e="{\"success\":false}";reply(c,500,"Internal Server Error","application/json",e,strlen(e));return;}size_t n=(size_t)ln;char*b=malloc(n?n:1);if(!b){fclose(fp);const char*e="{\"success\":false}";reply(c,500,"Internal Server Error","application/json",e,strlen(e));return;}if(fread(b,1,n,fp)==n)reply(c,200,"OK",mime(f),b,n);else{const char*e="{\"success\":false}";reply(c,500,"Internal Server Error","application/json",e,strlen(e));}free(b);fclose(fp);}

typedef struct{uint32_t h[5];uint64_t bytes;unsigned char b[64];size_t used;}SHA1;
static uint32_t rol(uint32_t v,unsigned n){return(v<<n)|(v>>(32-n));}
static void sha_block(SHA1*c,const unsigned char*b){uint32_t w[80];for(int i=0;i<16;i++)w[i]=((uint32_t)b[4*i]<<24)|((uint32_t)b[4*i+1]<<16)|((uint32_t)b[4*i+2]<<8)|b[4*i+3];for(int i=16;i<80;i++)w[i]=rol(w[i-3]^w[i-8]^w[i-14]^w[i-16],1);uint32_t a=c->h[0],bb=c->h[1],cc=c->h[2],d=c->h[3],e=c->h[4];for(int i=0;i<80;i++){uint32_t f,k;if(i<20){f=(bb&cc)|((~bb)&d);k=0x5A827999;}else if(i<40){f=bb^cc^d;k=0x6ED9EBA1;}else if(i<60){f=(bb&cc)|(bb&d)|(cc&d);k=0x8F1BBCDC;}else{f=bb^cc^d;k=0xCA62C1D6;}uint32_t t=rol(a,5)+f+e+k+w[i];e=d;d=cc;cc=rol(bb,30);bb=a;a=t;}c->h[0]+=a;c->h[1]+=bb;c->h[2]+=cc;c->h[3]+=d;c->h[4]+=e;}
static void sha_init(SHA1*c){c->h[0]=0x67452301;c->h[1]=0xEFCDAB89;c->h[2]=0x98BADCFE;c->h[3]=0x10325476;c->h[4]=0xC3D2E1F0;c->bytes=0;c->used=0;}
static void sha_update(SHA1*c,const void*data,size_t n){const unsigned char*p=data;c->bytes+=n;while(n){size_t t=64-c->used;if(t>n)t=n;memcpy(c->b+c->used,p,t);c->used+=t;p+=t;n-=t;if(c->used==64){sha_block(c,c->b);c->used=0;}}}
static void sha_final(SHA1*c,unsigned char out[20]){uint64_t bits=c->bytes*8;c->b[c->used++]=0x80;if(c->used>56){while(c->used<64)c->b[c->used++]=0;sha_block(c,c->b);c->used=0;}while(c->used<56)c->b[c->used++]=0;for(int i=7;i>=0;i--)c->b[c->used++]=(unsigned char)(bits>>(i*8));sha_block(c,c->b);for(int i=0;i<5;i++){out[4*i]=c->h[i]>>24;out[4*i+1]=c->h[i]>>16;out[4*i+2]=c->h[i]>>8;out[4*i+3]=c->h[i];}}
static void b64(const unsigned char*in,size_t n,char*out,size_t os){static const char*t="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";size_t i=0,o=0;while(i<n&&o+4<os){size_t r=n-i;uint32_t v=(uint32_t)in[i]<<16;if(r>1)v|=(uint32_t)in[i+1]<<8;if(r>2)v|=in[i+2];out[o++]=t[(v>>18)&63];out[o++]=t[(v>>12)&63];out[o++]=r>1?t[(v>>6)&63]:'=';out[o++]=r>2?t[v&63]:'=';i+=r>=3?3:r;}if(o<os)out[o]=0;}
static int header(const char*req,const char*name,char*out,size_t n){size_t nl=strlen(name);const char*p=req;while((p=strcasestr(p,name))){if((p==req||p[-1]=='\n')&&!strncasecmp(p,name,nl)&&p[nl]==':'){p+=nl+1;while(*p==' '||*p=='\t')p++;const char*e=strstr(p,"\r\n");if(!e)return 0;size_t l=(size_t)(e-p);if(l>=n)l=n-1;memcpy(out,p,l);out[l]=0;return 1;}p+=nl;}return 0;}
static int header_token(const char*req,const char*name,const char*token){char v[512];if(!header(req,name,v,sizeof v))return 0;char*p=v;while(*p){while(*p==' '||*p=='\t'||*p==',')p++;char*e=p;while(*e&&*e!=',')e++;char*trim=e;while(trim>p&&(trim[-1]==' '||trim[-1]=='\t'))trim--;size_t n=(size_t)(trim-p);if(strlen(token)==n&&!strncasecmp(p,token,n))return 1;p=*e?e+1:e;}return 0;}
static int origin_ok(const char*req){char origin[512],host[256];if(!header(req,"Origin",origin,sizeof origin))return 1;if(!header(req,"Host",host,sizeof host))return 0;const char*p=NULL;if(!strncasecmp(origin,"http://",7))p=origin+7;else if(!strncasecmp(origin,"https://",8))p=origin+8;else return 0;const char*slash=strchr(p,'/');size_t n=slash?(size_t)(slash-p):strlen(p);return strlen(host)==n&&!strncasecmp(host,p,n);}
static int path_ok(const char*p){return!strcmp(p,"/health")||!strcmp(p,"/status")||!strcmp(p,"/state")||!strcmp(p,"/devices")||!strcmp(p,"/discovered")||!strcmp(p,"/history")||!strncmp(p,"/devices/",9);}
static int ws_handshake(int c,const char*req){char key[256],version[32];if(!header(req,"Sec-WebSocket-Key",key,sizeof key)||!header(req,"Sec-WebSocket-Version",version,sizeof version)||strcmp(version,"13")||!header_token(req,"Connection","Upgrade")||!origin_ok(req))return-1;char x[512];snprintf(x,sizeof x,"%s258EAFA5-E914-47DA-95CA-C5AB0DC85B11",key);unsigned char dig[20];SHA1 s;sha_init(&s);sha_update(&s,x,strlen(x));sha_final(&s,dig);char acc[64];b64(dig,20,acc,sizeof acc);char h[512];int n=snprintf(h,sizeof h,"HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Accept: %s\r\n\r\n",acc);return n>0?sendall(c,h,(size_t)n):-1;}
static int ws_send(int c,unsigned op,const void*data,size_t n){unsigned char h[10];size_t hn=0;h[hn++]=0x80|(op&15);if(n<126)h[hn++]=(unsigned char)n;else if(n<=65535){h[hn++]=126;h[hn++]=n>>8;h[hn++]=n;}else{h[hn++]=127;uint64_t v=n;for(int i=7;i>=0;i--)h[hn++]=(unsigned char)(v>>(8*i));}if(sendall(c,h,hn)<0)return-1;return n?sendall(c,data,n):0;}
static int ws_text(int c,const char*s){return ws_send(c,1,s,strlen(s));}
static int ws_read(int c,char**out){*out=NULL;for(;;){unsigned char h[2];if(recvall(c,h,2)<=0)return 0;unsigned op=h[0]&15,fin=h[0]>>7,mask=h[1]>>7,rsv=h[0]&0x70;uint64_t n=h[1]&127;if(rsv||!mask||((op&8)&&(!fin||n>125)))return-1;if(n==126){unsigned char x[2];if(recvall(c,x,2)<=0)return 0;n=((uint64_t)x[0]<<8)|x[1];}else if(n==127){unsigned char x[8];if(recvall(c,x,8)<=0)return 0;n=0;for(int i=0;i<8;i++)n=(n<<8)|x[i];}if(n>MAX_PAYLOAD)return-1;unsigned char m[4]={0};if(mask&&recvall(c,m,4)<=0)return 0;unsigned char*p=malloc((size_t)n+1);if(!p)return-1;if(n&&recvall(c,p,(size_t)n)<=0){free(p);return 0;}if(mask)for(uint64_t i=0;i<n;i++)p[i]^=m[i&3];p[n]=0;if(op==8){free(p);ws_send(c,8,NULL,0);return 0;}if(op==9){ws_send(c,10,p,(size_t)n);free(p);continue;}if(op==10){free(p);continue;}if(op!=1||!fin){free(p);return-1;}*out=(char*)p;return 1;}}

static int proxy(const char*method,const char*path,const char*body,int*status,char**resp){*status=503;*resp=NULL;int s=socket(AF_UNIX,SOCK_STREAM,0);if(s<0)return-1;struct sockaddr_un a={.sun_family=AF_UNIX};strncpy(a.sun_path,SOCK_PATH,sizeof(a.sun_path)-1);if(connect(s,(struct sockaddr*)&a,sizeof a)<0){close(s);return-1;}size_t bl=body?strlen(body):0,cap=strlen(method)+strlen(path)+bl+512;char*q=malloc(cap);if(!q){close(s);return-1;}int qn=snprintf(q,cap,"%s /api%s HTTP/1.1\r\nHost: localhost\r\nContent-Type: application/json\r\nContent-Length: %zu\r\nConnection: close\r\n\r\n%s",method,path,bl,body?body:"");if(qn<0||sendall(s,q,(size_t)qn)<0){free(q);close(s);return-1;}free(q);cap=8192;size_t used=0;char*b=malloc(cap);if(!b){close(s);return-1;}for(;;){if(used+4096+1>cap){cap*=2;if(cap>2*MAX_PAYLOAD){free(b);close(s);return-1;}char*nb=realloc(b,cap);if(!nb){free(b);close(s);return-1;}b=nb;}ssize_t r=read(s,b+used,cap-used-1);if(r<0){if(errno==EINTR)continue;free(b);close(s);return-1;}if(!r)break;used+=r;}close(s);b[used]=0;int st=502;sscanf(b,"HTTP/%*d.%*d %d",&st);char*sep=strstr(b,"\r\n\r\n");*resp=strdup(sep?sep+4:"");*status=st;free(b);return*resp?0:-1;}
static int method_ok(const char*m){return!strcmp(m,"GET")||!strcmp(m,"POST")||!strcmp(m,"PUT")||!strcmp(m,"DELETE");}
static void ws_error(int c,int64_t id,int st,const char*msg){json_object*o=json_object_new_object(),*d=json_object_new_object();json_object_object_add(o,"type",json_object_new_string("response"));json_object_object_add(o,"id",json_object_new_int64(id));json_object_object_add(o,"status",json_object_new_int(st));json_object_object_add(d,"success",json_object_new_boolean(0));json_object_object_add(d,"message",json_object_new_string(msg));json_object_object_add(o,"data",d);ws_text(c,json_object_to_json_string_ext(o,JSON_C_TO_STRING_PLAIN));json_object_put(o);}
static int ws_message(int c,const char*msg){json_object*q=json_tokener_parse(msg);if(!q||!json_object_is_type(q,json_type_object)){if(q)json_object_put(q);ws_error(c,0,400,"invalid websocket message");return 0;}json_object*v=NULL;int64_t id=0;if(json_object_object_get_ex(q,"id",&v))id=json_object_get_int64(v);const char*m=NULL,*p=NULL;if(json_object_object_get_ex(q,"method",&v))m=json_object_get_string(v);if(json_object_object_get_ex(q,"path",&v))p=json_object_get_string(v);if(!m||!p||!method_ok(m)||!path_ok(p)||strchr(p,'\r')||strchr(p,'\n')){json_object_put(q);ws_error(c,id,400,"invalid method or path");return 0;}char*body=strdup("");if(json_object_object_get_ex(q,"body",&v)){free(body);body=strdup(json_object_to_json_string_ext(v,JSON_C_TO_STRING_PLAIN));}int st;char*rb=NULL;if(!body||proxy(m,p,body,&st,&rb)<0){free(body);free(rb);json_object_put(q);ws_error(c,id,503,"service unavailable");return 0;}free(body);json_object*d=json_tokener_parse(rb);if(!d)d=json_object_new_string(rb);free(rb);json_object*o=json_object_new_object();json_object_object_add(o,"type",json_object_new_string("response"));json_object_object_add(o,"id",json_object_new_int64(id));json_object_object_add(o,"status",json_object_new_int(st));json_object_object_add(o,"data",d);int rc=ws_text(c,json_object_to_json_string_ext(o,JSON_C_TO_STRING_PLAIN));json_object_put(o);json_object_put(q);return rc;}
static int push_state(int c){int st;char*rb=NULL;if(proxy("GET","/state","",&st,&rb)<0)return 0;if(st!=200){free(rb);return 0;}json_object*d=json_tokener_parse(rb);free(rb);if(!d)return 0;json_object*o=json_object_new_object();json_object_object_add(o,"type",json_object_new_string("state"));json_object_object_add(o,"data",d);int rc=ws_text(c,json_object_to_json_string_ext(o,JSON_C_TO_STRING_PLAIN));json_object_put(o);return rc;}
static void ws_loop(int c){if(push_state(c)<0)return;for(;;){struct pollfd p={.fd=c,.events=POLLIN};int r=poll(&p,1,1000);if(r<0){if(errno==EINTR)continue;break;}if(!r){if(push_state(c)<0)break;continue;}if(p.revents&(POLLERR|POLLHUP|POLLNVAL))break;if(p.revents&POLLIN){char*m=NULL;int rr=ws_read(c,&m);if(rr<=0){free(m);break;}int rc=ws_message(c,m);free(m);if(rc<0)break;if(push_state(c)<0)break;}}}
static void handle(int c){char b[65536];ssize_t n=read_headers(c,b,sizeof b);if(n<=0)return;b[n]=0;char method[8],path[256];if(sscanf(b,"%7s %255s",method,path)!=2)return;if(strcmp(method,"GET")){const char*e="{\"success\":false,\"message\":\"method not allowed\"}";reply(c,405,"Method Not Allowed","application/json",e,strlen(e));return;}if(!strcmp(path,"/ws")){char up[64]={0};if(!header(b,"Upgrade",up,sizeof up)||strcasecmp(up,"websocket")){const char*e="{\"success\":false,\"message\":\"websocket upgrade required\"}";reply(c,426,"Upgrade Required","application/json",e,strlen(e));return;}if(ws_handshake(c,b)==0)ws_loop(c);else{const char*e="{\"success\":false,\"message\":\"invalid websocket handshake or origin\"}";reply(c,400,"Bad Request","application/json",e,strlen(e));}return;}if(!strncmp(path,"/api/",5)){const char*e="{\"success\":false,\"message\":\"HTTP API disabled; use WebSocket /ws\"}";reply(c,426,"Upgrade Required","application/json",e,strlen(e));return;}static_file(c,path);}
static void load_settings(char*bindip,size_t n,int*port){snprintf(bindip,n,"%s","0.0.0.0");*port=5000;json_object*j=json_object_from_file(SETTINGS),*v=NULL;if(!j)return;if(json_object_object_get_ex(j,"bind_address",&v)&&json_object_is_type(v,json_type_string)){const char*s=json_object_get_string(v);if(s&&*s)snprintf(bindip,n,"%s",s);}if(json_object_object_get_ex(j,"web_port",&v)){int p=json_object_get_int(v);if(p>0&&p<=65535)*port=p;}json_object_put(j);}
int main(int argc,char**argv){signal(SIGPIPE,SIG_IGN);signal(SIGCHLD,SIG_IGN);char bindcfg[64];int port;load_settings(bindcfg,sizeof bindcfg,&port);const char*bindip=argc>1?argv[1]:bindcfg;if(argc>2){char*end=NULL;long p=strtol(argv[2],&end,10);if(!end||*end||p<1||p>65535){fprintf(stderr,"parental-control-web: invalid port\n");return 1;}port=(int)p;}int s=socket(AF_INET,SOCK_STREAM,0),one=1;if(s<0)return 1;setsockopt(s,SOL_SOCKET,SO_REUSEADDR,&one,sizeof one);struct sockaddr_in a={.sin_family=AF_INET,.sin_port=htons((uint16_t)port)};if(inet_pton(AF_INET,bindip,&a.sin_addr)!=1||bind(s,(struct sockaddr*)&a,sizeof a)||listen(s,32)){perror("parental-control-web");close(s);return 1;}for(;;){int c=accept(s,NULL,NULL);if(c<0){if(errno==EINTR)continue;break;}pid_t p=fork();if(!p){close(s);handle(c);close(c);_exit(0);}close(c);}close(s);return 0;}
