#!/bin/sh /etc/rc.common
START=95
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/parental-control
	procd_set_param respawn 3600 5 5
	procd_set_param file /etc/parental-control/devices.json /etc/parental-control/settings.json
	procd_close_instance
}

stop_service() {
	service_stop /usr/sbin/parental-control
	/usr/sbin/nft 'destroy table inet parental_control' >/dev/null 2>&1 || /usr/bin/nft 'destroy table inet parental_control' >/dev/null 2>&1 || true
	rm -f /var/run/parental-control.sock /var/run/parental-control.nft
}
